Validate release prep (#85)
* validate the main branch is up to date with the release

* adding RULESET to upgrade script

* revert ruleset

* update deps.

* assume there is a update deps file

* be very clear on the domain

* update to no set env

* add manual, remove set-env

* action will pass and test outputs of failed commands.

* oops, typo on var

* adding some comments

* spell mo betta

* stdout

diff --git a/.github/workflows/knative-releasability.yaml b/.github/workflows/knative-releasability.yaml
--- a/.github/workflows/knative-releasability.yaml
+++ b/.github/workflows/knative-releasability.yaml
@@ -19,7 +19,9 @@ name: 'Releasability'
 
 on:
   schedule:
-  - cron: '0 5 * * 1-5' # 5am, robot time, weekdays.
+    - cron: '0 5 * * 1-5' # 5am, robot time, weekdays.
+
+  workflow_dispatch:    # Manual trigger.
 
 jobs:
   releasability:
@@ -40,35 +42,68 @@ jobs:
           go-version: 1.15.x
 
       - name: Install Dependencies
-        run: |
-          GO111MODULE=on go get tableflip.dev/buoy@master
+        run: GO111MODULE=on go get tableflip.dev/buoy@master
 
       - name: Check out code
         uses: actions/checkout@v2
+        with:
+          path: ./src/knative.dev/${{ github.event.repository.name }}
 
       - name: Check
         run: |
-          buoy check go.mod --release $RELEASE --verbose
+          # The following pushes the stdout of buoy into $CHECK_MESSAGE
+          echo 'CHECK_MESSAGE<<EOF' >> $GITHUB_ENV
+          (buoy check go.mod --release ${RELEASE} --domain knative.dev --verbose || CHECK=$?) >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+
+          # We just captured the return code of the buoy call, test it to see
+          # if we should contiue validating. The next steps short circuit if
+          # we already know we are not ready for a release.
+          if [[ "$CHECK" -eq "0"  ]]; then
+            echo 'current=true' >> $GITHUB_ENV
+          else
+            echo 'current=false' >> $GITHUB_ENV
+          fi
+
+      - name: Upgrade
+        if: env.current == 'true'
+        run: |
+          # if update deps returns un-successful, then mark current to false.
+          if ! ./hack/update-deps.sh --release ${RELEASE} --upgrade; then
+            echo 'current=false' >> $GITHUB_ENV
+          fi
+
+      - name: Verify
+        if: env.current == 'true'
+        run: |
+          # If we see no changes after the upgrade, then we are up to date.
+          if [[ -z "$(git status --porcelain)" ]]; then
+              echo "VERIFY_MESSAGE=${{ github.repository }} up to date." >> $GITHUB_ENV
+          else
+              echo "VERIFY_MESSAGE=${{ github.repository }} is out of date." >> $GITHUB_ENV
+              echo 'current=false' >> $GITHUB_ENV
+          fi
 
       - name: Status GO
-        if: ${{ success() }}
+        if: env.current == 'true'
         run: |
-          echo "::set-env name=SLACK_COLOR::'#098e00'"
-          echo "::set-env name=SLACK_TITLE::Releasability for ${{ github.repository }} @ ${RELEASE} is GO!"
+          echo 'SLACK_COLOR=#098e00' >> $GITHUB_ENV
+          echo 'SLACK_TITLE=Releasability for ${{ github.repository }} @ ${RELEASE} is GO!' >> $GITHUB_ENV
 
       - name: Status NO-GO
-        if: ${{ failure() }}
+        if: env.current == 'false'
         run: |
-          echo "::set-env name=SLACK_COLOR::'#8E1600'"
-          echo "::set-env name=SLACK_TITLE::Releasability for ${{ github.repository }} @ ${RELEASE} is NO-GO!"
+          echo 'SLACK_COLOR=#8E1600' >> $GITHUB_ENV
+          echo 'SLACK_TITLE=Releasability for ${{ github.repository }} @ ${RELEASE} is NO-GO!' >> $GITHUB_ENV
 
       - name: Post notice to Slack
         uses: rtCamp/action-slack-notify@v2.1.0
-        if: ${{ always() }}
         env:
           SLACK_ICON: http://github.com/knative.png?size=48
           SLACK_USERNAME: github-actions
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           MSG_MINIMAL: 'true'
           SLACK_MESSAGE: |
+            ${CHECK_MESSAGE}
+            ${VERIFY_MESSAGE}
             For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
